dependencies:
  '@babel/parser': 7.4.5
  '@babel/types': 7.4.4
  '@rush-temp/shift-babel-macro': 'file:projects/shift-babel-macro.tgz'
  '@types/node': 10.14.9
  babel-plugin-macros: 2.6.1
  typescript: 3.5.2
packages:
  /@babel/parser/7.4.5:
    dev: false
    engines:
      node: '>=6.0.0'
    hasBin: true
    resolution:
      integrity: sha512-9mUqkL1FF5T7f0WDFfAoDdiMVPWsdD1gZYzSnaXsxUCUqzuch/8of9G3VUSNiZmMBoRxT3neyVsqeiL/ZPcjew==
  /@babel/runtime/7.4.5:
    dependencies:
      regenerator-runtime: 0.13.2
    dev: false
    resolution:
      integrity: sha512-TuI4qpWZP6lGOGIuGWtp9sPluqYICmbk8T/1vpSysqJxRPkudh/ofFWyqdcMsDf2s7KvDL4/YHgKyvcS3g9CJQ==
  /@babel/types/7.4.4:
    dependencies:
      esutils: 2.0.2
      lodash: 4.17.11
      to-fast-properties: 2.0.0
    dev: false
    resolution:
      integrity: sha512-dOllgYdnEFOebhkKCjzSVFqw/PmmB8pH6RGOWkY4GsboQNd47b1fBThBSwlHAq9alF9vc1M3+6oqR47R50L0tQ==
  /@types/node/10.14.9:
    dev: false
    resolution:
      integrity: sha512-NelG/dSahlXYtSoVPErrp06tYFrvzj8XLWmKA+X8x0W//4MqbUyZu++giUG/v0bjAT6/Qxa8IjodrfdACyb0Fg==
  /argparse/1.0.10:
    dependencies:
      sprintf-js: 1.0.3
    dev: false
    resolution:
      integrity: sha512-o5Roy6tNG4SL/FOkCAN6RzjiakZS25RLYFrcMttJqbdd8BWrnA+fGz57iN5Pb06pvBGvl5gQ0B48dJlslXvoTg==
  /babel-plugin-macros/2.6.1:
    dependencies:
      '@babel/runtime': 7.4.5
      cosmiconfig: 5.2.1
      resolve: 1.11.0
    dev: false
    resolution:
      integrity: sha512-6W2nwiXme6j1n2erPOnmRiWfObUhWH7Qw1LMi9XZy8cj+KtESu3T6asZvtk5bMQQjX8te35o7CFueiSdL/2NmQ==
  /caller-callsite/2.0.0:
    dependencies:
      callsites: 2.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-hH4PzgoiN1CpoCfFSzNzGtMVQTQ=
  /caller-path/2.0.0:
    dependencies:
      caller-callsite: 2.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-Ro+DBE42mrIBD6xfBs7uFbsssfQ=
  /callsites/2.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-BuuE8A7qQT2oav/vrL/7Ngk7PFA=
  /cosmiconfig/5.2.1:
    dependencies:
      import-fresh: 2.0.0
      is-directory: 0.3.1
      js-yaml: 3.13.1
      parse-json: 4.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha512-H65gsXo1SKjf8zmrJ67eJk8aIRKV5ff2D4uKZIBZShbhGSpEmsQOPW/SKMKYhSTrqR7ufy6RP69rPogdaPh/kA==
  /error-ex/1.3.2:
    dependencies:
      is-arrayish: 0.2.1
    dev: false
    resolution:
      integrity: sha512-7dFHNmqeFSEt2ZBsCriorKnn3Z2pj+fd9kmI6QoWw4//DL+icEBfc0U7qJCisqrTsKTjw4fNFy2pW9OqStD84g==
  /esprima/4.0.1:
    dev: false
    engines:
      node: '>=4'
    hasBin: true
    resolution:
      integrity: sha512-eGuFFw7Upda+g4p+QHvnW0RyTX/SVeJBDM/gCtMARO0cLuT2HcEKnTPvhjV6aGeqrCB/sbNop0Kszm0jsaWU4A==
  /esutils/2.0.2:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-Cr9PHKpbyx96nYrMbepPqqBLrJs=
  /import-fresh/2.0.0:
    dependencies:
      caller-path: 2.0.0
      resolve-from: 3.0.0
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-2BNVwVYS04bGH53dOSLUMEgipUY=
  /is-arrayish/0.2.1:
    dev: false
    resolution:
      integrity: sha1-d8mYQFJ6qOyxqLppe4BkWnqSap0=
  /is-directory/0.3.1:
    dev: false
    engines:
      node: '>=0.10.0'
    resolution:
      integrity: sha1-YTObbyR1/Hcv2cnYP1yFddwVSuE=
  /js-yaml/3.13.1:
    dependencies:
      argparse: 1.0.10
      esprima: 4.0.1
    dev: false
    hasBin: true
    resolution:
      integrity: sha512-YfbcO7jXDdyj0DGxYVSlSeQNHbD7XPWvrVWeVUujrQEoZzWJIRrCPoyk6kL6IAjAG2IolMK4T0hNUe0HOUs5Jw==
  /json-parse-better-errors/1.0.2:
    dev: false
    resolution:
      integrity: sha512-mrqyZKfX5EhL7hvqcV6WG1yYjnjeuYDzDhhcAAUrq8Po85NBQBJP+ZDUT75qZQ98IkUoBqdkExkukOU7Ts2wrw==
  /lodash/4.17.11:
    dev: false
    resolution:
      integrity: sha512-cQKh8igo5QUhZ7lg38DYWAxMvjSAKG0A8wGSVimP07SIUEK2UO+arSRKbRZWtelMtN5V0Hkwh5ryOto/SshYIg==
  /parse-json/4.0.0:
    dependencies:
      error-ex: 1.3.2
      json-parse-better-errors: 1.0.2
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-vjX1Qlvh9/bHRxhPmKeIy5lHfuA=
  /path-parse/1.0.6:
    dev: false
    resolution:
      integrity: sha512-GSmOT2EbHrINBf9SR7CDELwlJ8AENk3Qn7OikK4nFYAu3Ote2+JYNVvkpAEQm3/TLNEJFD/xZJjzyxg3KBWOzw==
  /regenerator-runtime/0.13.2:
    dev: false
    resolution:
      integrity: sha512-S/TQAZJO+D3m9xeN1WTI8dLKBBiRgXBlTJvbWjCThHWZj9EvHK70Ff50/tYj2J/fvBY6JtFVwRuazHN2E7M9BA==
  /resolve-from/3.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-six699nWiBvItuZTM17rywoYh0g=
  /resolve/1.11.0:
    dependencies:
      path-parse: 1.0.6
    dev: false
    resolution:
      integrity: sha512-WL2pBDjqT6pGUNSUzMw00o4T7If+z4H2x3Gz893WoUQ5KW8Vr9txp00ykiP16VBaZF5+j/OcXJHZ9+PCvdiDKw==
  /sprintf-js/1.0.3:
    dev: false
    resolution:
      integrity: sha1-BOaSb2YolTVPPdAVIDYzuFcpfiw=
  /to-fast-properties/2.0.0:
    dev: false
    engines:
      node: '>=4'
    resolution:
      integrity: sha1-3F5pjL0HkmW8c+A3doGk5Og/YW4=
  /typescript/3.5.2:
    dev: false
    engines:
      node: '>=4.2.0'
    hasBin: true
    resolution:
      integrity: sha512-7KxJovlYhTX5RaRbUdkAXN1KUZ8PwWlTzQdHV6xNqvuFOs7+WBo10TQUqT19Q/Jz2hk5v9TQDIhyLhhJY4p5AA==
  'file:projects/shift-babel-macro.tgz':
    dependencies:
      '@babel/parser': 7.4.5
      '@babel/types': 7.4.4
      '@types/node': 10.14.9
      babel-plugin-macros: 2.6.1
      typescript: 3.5.2
    dev: false
    name: '@rush-temp/shift-babel-macro'
    resolution:
      integrity: sha512-JR3Ht93lw0Rt4s2NxOC9W0WF1R7NIYKrQrD1ns9MRdzS8R16+Ww3Dc2S6iQZISBFGKVvYU7y84hniyOfBR9Wgg==
      tarball: 'file:projects/shift-babel-macro.tgz'
    version: 0.0.0
registry: 'https://registry.npmjs.org/'
shrinkwrapMinorVersion: 9
shrinkwrapVersion: 3
specifiers:
  '@babel/parser': ^7.4.5
  '@babel/types': ^7.4.4
  '@rush-temp/shift-babel-macro': 'file:./projects/shift-babel-macro.tgz'
  '@types/node': ^10.14.9
  babel-plugin-macros: ^2.6.0
  typescript: ^3.5.2
