version: 2.1
aliases:
  - &docker
    docker:
      - image: circleci/node:10
  - &attach_workspace
    - attach_workspace:
        at: .
jobs:
  build:
    <<: *docker
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "common/config/rush/shrinkwrap.yaml" }}
      - run:
          name: Generate interface packages
          command: scripts/generate_interfaces
      - run:
          name: Install dependencies
          command: node common/scripts/install-run-rush.js install
      - save_cache:
          key: dependency-cache-{{ checksum "common/config/rush/shrinkwrap.yaml" }}
          paths:
            - common/temp
            - ~/.rush
      - run:
          name: Build source
          command: node common/scripts/install-run-rush.js rebuild --verbose
      - persist_to_workspace:
          root: .
          paths:
            - '*/dist'
            - '*/node_modules'
            - common/temp
            - gen-server
            - gen-client
  lint:
    <<: *docker
    steps:
      - checkout
      - <<: *attach_workspace
      - run:
          name: Run lint
          command: node common/scripts/install-run-rush.js lint
  test:
    <<: *docker
    steps:
      - checkout
      - <<: *attach_workspace
      - run: # Once the packages are public this can be removed
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Run tests
          command: node common/scripts/install-run-rush.js test --verbose
  verify_change_logs:
    <<: *docker
    steps:
      - checkout
      # Only so rush changes can work; it will never understand something has changed.
      - <<: *attach_workspace
      - run:
          name: Check for missing change logs
          command: |
            git fetch origin master:refs/remotes/origin/master -a
            node common/scripts/install-run-rush.js change --verify
  update_npm_dependencies:
    <<: *docker
    steps:
      - checkout
      - run:
          name: Configure git
          command: |
            git config user.email "auto-npm-dep-update@shiftjs.com"
            git config user.name "autoupdate"
      - run:
          name: Update npm dependencies
          command: node common/scripts/install-run.js rush-update@latest rush-update -x @types/node --repo-owner binaris --repo-name shiftjs --pr-reviewers michaeladda
workflows:
  version: 2
  commit:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                # according to https://circleci.com/docs/2.0/configuration-reference/#filters-1
                # regex should capture the whole string, so not /^publish-/
                - /publish-.*/
      - lint:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /publish-.*/
      - test:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /publish-.*/
      - verify_change_logs:
          requires:
            - build
          filters:
            branches:
              ignore:
                - /publish-.*/
  weekly:
    triggers:
       - schedule:
           cron: "0 0 * * 5"
           filters:
             branches:
               only:
                 - master
    jobs:
      - update_npm_dependencies
