version: 2.1
aliases:
  &docker
    docker:
      - image: circleci/node:10
jobs:
  build_and_test:
    <<: *docker
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "common/config/rush/shrinkwrap.yaml" }}
      - run:
          name: Install dependencies
          command: node common/scripts/install-run-rush.js install
      - save_cache:
          key: dependency-cache-{{ checksum "common/config/rush/shrinkwrap.yaml" }}
          paths:
            - common/temp
            - ~/.rush
      - run:
          name: Build source
          command: node common/scripts/install-run-rush.js rebuild --verbose
      - run:
          name: Run lint
          command: node common/scripts/install-run-rush.js lint
      - run:
          name: Run tests
          command: node common/scripts/install-run-rush.js test --verbose
  verify_change_logs:
    <<: *docker
    steps:
      - checkout
      - run:
          name: Check for missing change logs
          command: |
            git fetch origin master:refs/remotes/origin/master -a
            node common/scripts/install-run-rush.js change --verify

  update_npm_dependencies:
    <<: *docker
    steps:
      - checkout
      - run:
          name: Configure git
          command: |
            git config user.email "auto-npm-dep-update@shiftjs.com"
            git config user.name "autoupdate"
      - run:
          name: Update npm dependencies
          command: node common/scripts/install-run.js rush-update@latest rush-update -x @types/node --repo-owner binaris --repo-name shiftjs
workflows:
  version: 2
  commit:
    jobs:
      - build_and_test
      - verify_change_logs
  nightly:
    triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
    jobs:
      - update_npm_dependencies
